# Generated by Django 4.0.4 on 2022-04-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUpload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
